name: Telegram Message Forwarder 2

on:
  schedule:
    - cron: '1 6 * * *'  # اجرای روزانه ساعت 00:01 UTC
  workflow_dispatch:      # اجازه اجرای دستی هم داشته باشه

jobs:
  run-telegram-script:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # حداکثر 6 ساعت اجرا

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install telethon

      - name: Run Telegram Forwarder
        run: |
          python manitoring.py
